// app state
export const START_CHAT_CONNECTION = 'START_CHAT_CONNECTION';

// Talk window actions
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SET_TALK_HISTORY = 'SET_TALK_HISTORY';
export const SET_DELAYED_MESSAGES = 'SET_DELAYED_MESSAGES';
export const PREPEND_TALK_HISTORY = 'PREPEND_TALK_HISTORY';
export const REMOVE_JID_HISTORY = 'REMOVE_JID_HISTORY';
export const REMOVE_JID_TALK_WINDOW = 'REMOVE_JID_TALK_WINDOW';

///
export const OPEN_TALK_WINDOW = 'OPEN_TALK_WINDOW';
export const CONTROL_TALK_WINDOW = 'CONTROL_TALK_WINDOW';
export const MESSAGES_SCROLLING_HISTORY = 'MESSAGES_SCROLLING_HISTORY';
export const REMOVE_JID_SCROLLING_HISTORY = 'REMOVE_JID_SCROLLING_HISTORY';
export const DELALYED_ARCHIEVE_MESSAGES_ADD = 'DELAYED_ARCHIEVE_MESSAGES_ADD';

// User list actions
export const INIT_CONTACTS_LIST = 'INIT_CONTACTS_LIST';
export const UPDATE_CONTACTS_LIST = 'UPDATE_CONTACTS_LIST';
export const SET_CONTACT_PRESENCE = 'SET_CONTACT_PRESENCE';
export const SET_CONTACT_UNREAD_MESSAGE = 'SET_CONTACT_UNREAD_MESSAGE';
export const UNSET_CONTACT_UNREAD_MESSAGE = 'UNSET_CONTACT_UNREAD_MESSAGE';

